GET http://localhost:8080/books
###


POST http://localhost:8080/books
Content-Type: application/json

{
    "id": "4",
    "title": "Dune",
    "author": "Frank Herbert"
}
###

DELETE http://localhost:8080/books/2
